# Generated by Django 5.2.4 on 2025-10-30 11:57

import storages.backends.s3
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=users.models.user_avatar_upload_path),
        ),
    ]
