# Generated by Django 5.2.4 on 2025-11-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    # Postgres: drop column only if it exists
                    "ALTER TABLE users_user DROP COLUMN IF EXISTS avatar;",
                    reverse_sql="""
                        -- optional: recreate column if needed (likely leave empty)
                    """
                ),
            ],
            state_operations=[
                # Keep model state in sync: tell Django the field is gone
                migrations.RemoveField(
                    model_name='user',
                    name='avatar',
                ),
            ],
        ),
    ]
